const toggle=document.querySelector('.menu-toggle');const links=document.querySelector('.nav-links');toggle?.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});

const lanyard=document.querySelector('#lanyard');
if(lanyard){let active=false,startX=0,startY=0,x=0,y=0;
  const move=(event)=>{if(!active)return;x=Math.max(-120,Math.min(120,event.clientX-startX));y=Math.max(-45,Math.min(130,event.clientY-startY));lanyard.style.setProperty('--drag-x',`${x}px`);lanyard.style.setProperty('--drag-y',`${y}px`);lanyard.style.setProperty('--drag-r',`${x/18}deg`)};
  const release=()=>{if(!active)return;active=false;lanyard.classList.remove('is-dragging');lanyard.style.transition='transform .8s cubic-bezier(.2,.9,.25,1.15)';lanyard.style.setProperty('--drag-x','0px');lanyard.style.setProperty('--drag-y','0px');lanyard.style.setProperty('--drag-r','0deg');x=0;y=0;setTimeout(()=>{lanyard.style.transition='';lanyard.style.animation='lanyard-swing 4.8s ease-in-out infinite'},820)};
  lanyard.addEventListener('pointerdown',(event)=>{active=true;startX=event.clientX-x;startY=event.clientY-y;lanyard.setPointerCapture(event.pointerId);lanyard.classList.add('is-dragging');lanyard.style.animation='none'});lanyard.addEventListener('pointermove',move);lanyard.addEventListener('pointerup',release);lanyard.addEventListener('pointercancel',release);
}

const themeToggle=document.querySelector('.theme-toggle');
const themeIcon=document.querySelector('.theme-icon');
const themeLabel=document.querySelector('.theme-label');
const preferredTheme=localStorage.getItem('stacey-theme');
if(preferredTheme==='light')document.body.classList.add('light-theme');
const syncThemeButton=()=>{const isLight=document.body.classList.contains('light-theme');themeIcon.textContent=isLight?'☾':'☼';themeLabel.textContent=isLight?'Dark':'Light';themeToggle?.setAttribute('aria-label',`Switch to ${isLight?'dark':'light'} mode`)};
syncThemeButton();
themeToggle?.addEventListener('click',()=>{document.body.classList.toggle('light-theme');localStorage.setItem('stacey-theme',document.body.classList.contains('light-theme')?'light':'dark');syncThemeButton()});

const projectData=[
  {number:'01 / FEATURED CASE STUDY',title:'LeaSense <em>PH</em>',type:'Data-driven property management system',description:'Web-based property management for small-to-medium rental operations in the Philippines, with integrated administrator and tenant workflows, payment verification, and analytics.',tags:['Laravel','React','FastAPI','PostgreSQL','Supabase']},
  {number:'02 / FULL-STACK',title:'CLA.<em>I.RE</em>',type:'AI-assisted cervical cytology analysis tool',description:'A PHP and MySQL web application designed to support cervical cytology screening workflows through an accessible digital interface.',tags:['PHP','MySQL','Tailwind CSS']},
  {number:'03 / BACKEND DEVELOPMENT',title:'Membr<em>Ease</em>',type:'PhilHealth member management system',description:'A database-backed companion system with secure login and CRUD-based workflows for organizing and managing member records.',tags:['PHP','MySQL','JavaScript']},
  {number:'04 / BUSINESS ANALYSIS',title:'cat<em>HOPia</em>',type:'2D game application',description:'A colorful Unity game where I supported planning, requirements analysis, creative direction, and the overall project workflow.',tags:['Unity','Visual Studio','Canva']}
];
const slides=[...document.querySelectorAll('.carousel-slide')];const dotsWrap=document.querySelector('.carousel-dots');let activeProject=0;
slides.forEach((_,index)=>{const dot=document.createElement('button');dot.type='button';dot.className='carousel-dot';dot.setAttribute('aria-label',`Show project ${index+1}`);dot.addEventListener('click',()=>showProject(index));dotsWrap?.appendChild(dot)});
const relativePosition=(index,active,total)=>{let diff=(index-active+total)%total;if(diff>total/2)diff-=total;return diff};
function showProject(index){activeProject=(index+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.className='carousel-slide';const pos=relativePosition(i,activeProject,slides.length);if(pos===0)slide.classList.add('is-active');else if(pos===-1)slide.classList.add('is-prev');else if(pos===1)slide.classList.add('is-next');else if(pos<0)slide.classList.add('is-far-prev');else slide.classList.add('is-far-next');slide.setAttribute('aria-current',pos===0?'true':'false')});const project=projectData[activeProject];document.querySelector('#carousel-number').textContent=project.number;document.querySelector('#carousel-title').innerHTML=project.title;document.querySelector('#carousel-type').textContent=project.type;document.querySelector('#carousel-description').textContent=project.description;document.querySelector('#carousel-tags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');document.querySelectorAll('.carousel-dot').forEach((dot,i)=>dot.classList.toggle('is-active',i===activeProject));document.querySelector('.carousel-count b').textContent=String(activeProject+1).padStart(2,'0')}
slides.forEach((slide,index)=>slide.addEventListener('click',()=>showProject(index)));document.querySelector('.carousel-prev')?.addEventListener('click',()=>showProject(activeProject-1));document.querySelector('.carousel-next')?.addEventListener('click',()=>showProject(activeProject+1));document.querySelector('.work-carousel')?.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')showProject(activeProject-1);if(event.key==='ArrowRight')showProject(activeProject+1)});showProject(0);
